export function genderToText(value) {
    switch (value) {
        case 1:
            return 'male';
        case 0:
            return 'female';
        case 2:
            return 'other';
    }
}

export function capitalizeFirstLetter(string) {
    return string.charAt(0).toUpperCase() + string.slice(1);
}

export function countPlays(posts) {
    let counter = 0;
    posts.forEach((post) => {
        counter += post.plays;
    })
    return counter
}




// Labels
export const labels = {
    en: {
        'my-profile': 'My profile',
        'user-since': 'User since',
        'email': 'Email',
        'register': 'Register',
        'password': 'Password',
        'login': 'Login',
        'dashboard': 'Dashboard',
        'logout': 'Logout',
        'back-to-app': 'Back to app',
        'plays': 'Plays',
        'followers': 'Followers',
        'posts': 'Posts',
        'recently-uploaded': 'Recently uploaded',
        'recently-followed': 'Recently followed',
        'id': 'ID',
        'title': 'Title',
        'description': 'Description',
        'date': 'Date',
        'post': 'Post',
        'file-path': 'File path',
        'cancel': 'Cancel',
        'update': 'Update',
        'updating': 'Updating',
        'edit-post': 'Edit post',
        'delete-sure': 'Are you sure you want to delete this post?',
        'delete-sure-desc': 'This action cannot be undone.',
        'delete': 'Delete',
        'edit': 'Edit',
        'welcome-login': 'Welcome back',
        'welcome-login1': 'Please login to your account',
        'welcome-register': 'Welcome',
        'welcome-register1': 'Please create an account',
        'valid-user-length': 'Username must be atleast 3 characters long',
        'valid-user-exist': 'Username already exists',
        'valid-password-match': 'Passwords do not match',
        'preferences': 'Preferences',
        'nsfw': 'NSFW',
        'nsfw-alt': 'Explicit content',
        'nsfw-sub': 'Show NSFW post(must be considered of legal age in your place of residence)',
        'theme': 'Theme',
        'theme-sub': 'Set theme of app(setted as navigator by default)',
        'theme-selector-options': { 'automatic': { val: 'default', label: 'automatic' }, 'light': { val: 'light', label: 'light' }, 'dark': { val: 'dark', label: 'dark' } },
        'profile': 'Profile',
        'profiles': 'Profile\'s',
        'username': 'username',
        'cpassword': 'confirm password',
        'upload': 'upload',
        'tags': 'tags',
        'category': 'category',
        'visibility': 'visibility',
        'visibility-options': { 'public': { label: 'available for everyone' }, 'private': { label: 'available for no one' }, 'no-listed': { label: 'available using link' } },
        'categories': { 'audiobook': { label: 'audiobook', value: 'audiobook' }, 'effects': { label: 'effects', value: 'effects' }, 'general': { label: 'general', value: 'general' }, 'music': { label: 'music', value: 'music' } },
        'follower': 'follower',
        'recent-posts': 'recent posts',
        'latest-comments': 'latest comments',
        'latest-posts': 'latests posts',
        'latest-followers': 'latest followers',
        'comments': 'comments',
        'no-posts': 'no posts',
        'no-comments': 'no comments',
        'no-followers': 'no followers',
        'go-back-app': 'Go back app',
        'settings': 'settings',
        'get-id': 'get id',
        'home': 'home',
        'change-profile-pic': 'Change profile picture',
        'save-changes': 'Save changes',
        'play': 'Play',
        'pause': 'Pause',
        'leave-comment': 'Leave a comment',
        'send': 'Send',
        'load-more': 'Load more',
        'post-uploaded': 'Post uploaded!',
        'uploading': 'Uploading...',
        'interlude-uploaded': 'Interlude uploaded!',
        'reply-sent': 'Reply sent',
        'comment-sent': 'Comment sent',
        'link-copied': 'Link copied to clipboard',
        'no-profile-info': 'You don\'t have profile information. Please fill out this form to use the app.',
        'stations': 'Stations',
        'my-stations': 'My stations',
        'no-stations': 'No stations yet',
        'new-station': 'New station',
        'edit-station': 'Edit station',
        'station-name': 'Station name',
        'select-tracks': 'Select tracks',
        'shuffle-tracks': 'Shuffle tracks',
        'create': 'Create',
        'save': 'Save',
        'playing': 'Playing',
        'play-all': 'Play all',
        'now-playing': 'Now playing',
        'more-from': 'More from',
        'interludes': 'Interludes',
        'interludes-desc': 'Record short clips that play between your tracks, as intros, outros, or credits. Make your station feel like real radio.',
        'interlude': 'Interlude',
        'your-interludes': 'Your interludes',
        'upload-interlude': 'Upload interlude',
        'delete-interlude': 'Delete interlude?',
        'delete-interlude-desc': 'This interlude will be permanently deleted. This cannot be undone.',
        'history': 'History',
        'listening-history': 'Listening history',
        'nothing-played': 'Nothing played yet. Start listening!',
        'search-users': 'Search users...',
        'no-users-found': 'No users found',
        'sign-in': 'Sign in',
        'sign-in-first': 'Please sign in first',
        'replying-to': 'Replying to',
        'reply': 'reply',
        'replies': 'replies',
        'post-author': 'Post author',
        'share': 'Share',
        'based-on-listening': 'Based on your listening',
        'discover': 'Discover',
        'tracks': 'tracks',
        'station-playing': 'Station playing',
        'intro': 'Intro',
        'between-tracks': 'Between tracks',
        'outro': 'Outro',
        'credit': 'Credit',
        'intro-desc': 'Plays when station starts',
        'between-desc': 'Plays between songs',
        'outro-desc': 'Plays when station or single track ends',
        'credit-desc': 'Short sign-off after your content',
        'logout-sure': 'Are you sure you want to logout?',
        'no-posts-found': 'No posts found',
        'bookmarks': 'Bookmarks',
        'no-bookmarks': 'No saved posts yet. Bookmark posts to find them here.',
        'notifications': 'Notifications',
        'no-notifications': 'No notifications yet'
    },
    es: {
        'my-profile': 'Mi perfil',
        'email': 'Correo electrónico',
        'password': 'Contraseña',
        'register': 'Registrarse',
        'login': 'Iniciar Sesión',
        'dashboard': 'Panel de Control',
        'logout': 'Cerrar Sesión',
        'back-to-app': 'Volver a la aplicación',
        'plays': 'Reproducciones',
        'followers': 'Seguidores',
        'posts': 'Publicaciones',
        'recently-uploaded': 'Recientemente subido',
        'recently-followed': 'Recientemente seguido',
        'id': 'ID',
        'title': 'Título',
        'description': 'Descripción',
        'date': 'Fecha',
        'post': 'Publicación',
        'file-path': 'Ruta del archivo',
        'cancel': 'Cancelar',
        'update': 'Actualizar',
        'updating': 'Actualizando',
        'edit-post': 'Editar publicación',
        'delete-sure': '¿Está seguro de que desea eliminar esta publicación?',
        'delete-sure-desc': 'Esta acción no se puede deshacer.',
        'delete': 'Eliminar',
        'edit': 'Editar',
        'welcome-login': 'Bienvenido de nuevo',
        'welcome-login1': 'Por favor inicie sesión en su cuenta',
        'welcome-register': 'Bienvenido',
        'welcome-register1': 'Por favor cree una cuenta',
        'valid-user-length': 'El nombre de usuario debe tener al menos 3 caracteres',
        'valid-user-exist': 'El nombre de usuario ya existe',
        'valid-password-match': 'Las contraseñas no coinciden',
        'preferences': 'Preferencias',
        'nsfw': 'NSFW',
        'nsfw-alt': 'Contenido explicito',
        'nsfw-sub': 'Mostrar publicaciones NSFW(debes ser considerado mayor de edad)',
        'theme': 'Tema',
        'theme-sub': 'Aplica el tema(Aplicado del navegador por defecto)',
        'theme-selector-options': { 'automatic': { val: 'default', label: 'automatico' }, 'light': { val: 'light', label: 'claro' }, 'dark': { val: 'dark', label: 'obscuro' } },
        'profile': 'Perfil',
        'profiles': 'Perfil de',
        'username': 'Nombre de usuario',
        'cpassword': 'Confirmar contraseña',
        'upload': 'Subir',
        'tags': 'Etiquetas',
        'category': 'Categorias',
        'visibility': 'Visibilidad',
        'visibility-options': { 'public': { label: 'Disponible para todos' }, 'private': { label: 'No disponible para nadie' }, 'no-listed': { label: 'Disponible solo atravez de vinculo' } },
        'categories': { 'audiobook': { label: 'audio libro', value: 'audiobook' }, 'effects': { label: 'efectos', value: 'effects' }, 'general': { label: 'general', value: 'general' }, 'music': { label: 'musica', value: 'music' } },
        'follower': 'Seguidor',
        'recent-posts': 'Publicaciones recientes',
        'latest-posts': 'Últimas publicaciones',
        'latest-followers': 'Últimos seguidores',
        'latest-comments': 'Últimos comentarios',
        'comments': 'Comentarios',
        'no-posts': 'Sin publicaciones',
        'no-comments': 'Sin comentarios',
        'no-followers': 'Sin seguidores',
        'go-back-app': 'Regresar',
        'settings': 'Configuraciones',
        'user-since': 'Usuario desde',
        'get-id': 'Obtener id',
        'home': 'Inicio',
        'change-profile-pic': 'Cambia imagen de perfil',
        'save-changes': 'Guardar cambios',
        'play': 'Reproducir',
        'pause': 'Pausar',
        'leave-comment': 'Dejar un comentario',
        'send': 'Enviar',
        'load-more': 'Cargar más',
        'post-uploaded': '¡Publicación subida!',
        'uploading': 'Subiendo...',
        'interlude-uploaded': '¡Interludio subido!',
        'reply-sent': 'Respuesta enviada',
        'comment-sent': 'Comentario enviado',
        'link-copied': 'Enlace copiado al portapapeles',
        'no-profile-info': 'No tienes información de perfil. Por favor completa este formulario para usar la app.',
        'stations': 'Estaciones',
        'my-stations': 'Mis estaciones',
        'no-stations': 'Sin estaciones aún',
        'new-station': 'Nueva estación',
        'edit-station': 'Editar estación',
        'station-name': 'Nombre de estación',
        'select-tracks': 'Seleccionar pistas',
        'shuffle-tracks': 'Mezclar pistas',
        'create': 'Crear',
        'save': 'Guardar',
        'playing': 'Reproduciendo',
        'play-all': 'Reproducir todo',
        'now-playing': 'Reproduciendo ahora',
        'more-from': 'Más de',
        'interludes': 'Interludios',
        'interludes-desc': 'Graba clips cortos que se reproducen entre tus pistas, como intros, outros o créditos. Haz que tu estación se sienta como radio real.',
        'interlude': 'Interludio',
        'your-interludes': 'Tus interludios',
        'upload-interlude': 'Subir interludio',
        'delete-interlude': '¿Eliminar interludio?',
        'delete-interlude-desc': 'Este interludio será eliminado permanentemente. Esta acción no se puede deshacer.',
        'history': 'Historial',
        'listening-history': 'Historial de escucha',
        'nothing-played': '¡Nada reproducido aún. Empieza a escuchar!',
        'search-users': 'Buscar usuarios...',
        'no-users-found': 'No se encontraron usuarios',
        'sign-in': 'Iniciar sesión',
        'sign-in-first': 'Por favor inicia sesión primero',
        'replying-to': 'Respondiendo a',
        'reply': 'respuesta',
        'replies': 'respuestas',
        'post-author': 'Autor de la publicación',
        'share': 'Compartir',
        'based-on-listening': 'Basado en tu escucha',
        'discover': 'Descubrir',
        'tracks': 'pistas',
        'station-playing': 'Estación reproduciendo',
        'intro': 'Intro',
        'between-tracks': 'Entre pistas',
        'outro': 'Outro',
        'credit': 'Crédito',
        'intro-desc': 'Se reproduce al iniciar la estación',
        'between-desc': 'Se reproduce entre canciones',
        'outro-desc': 'Se reproduce al terminar la estación o una pista',
        'credit-desc': 'Despedida corta después de tu contenido',
        'logout-sure': '¿Estás seguro de que deseas cerrar sesión?',
        'no-posts-found': 'No se encontraron publicaciones',
        'bookmarks': 'Guardados',
        'no-bookmarks': 'Sin publicaciones guardadas aún. Guarda publicaciones para encontrarlas aquí.',
        'notifications': 'Notificaciones',
        'no-notifications': 'Sin notificaciones aún'
    }
}

export const firebaseErrorsMessages = {
    en: {
        'auth/email-already-in-use': 'Email already in use',
        'auth/invalid-email': 'Invalid email',
        'auth/user-not-found': 'User not found',
        'auth/wrong-password': 'Wrong password',
        'auth/too-many-requests': 'Too many requests',
        'auth/user-disabled': 'User disabled',
        'auth/operation-not-allowed': 'Operation not allowed',
        'auth/weak-password': 'Weak password',
        'auth/internal-error': 'Internal error',
        'auth/invalid-phone-number': 'Invalid phone number',
        'auth/invalid-verification-code': 'Invalid verification code',
        'auth/missing-phone-number': 'Missing phone number',
        'auth/missing-verification-code': 'Missing verification code',
        'auth/credential-already-in-use': 'Credential already in use',
        'auth/invalid-credential': 'Invalid credential',
        'auth/operation-not-supported-in-this-environment': 'Operation not supported in this environment',
        'auth/invalid-api-key': 'Invalid API key',
        'auth/invalid-user-token': 'Invalid user token',
        'auth/app-deleted': 'App deleted',
    },
    es: {
        'auth/email-already-in-use': 'Email ya en uso',
        'auth/invalid-email': 'Email inválido',
        'auth/user-not-found': 'Usuario no encontrado',
        'auth/wrong-password': 'Contraseña incorrecta',
        'auth/too-many-requests': 'Demasiadas solicitudes',
        'auth/user-disabled': 'Usuario deshabilitado',
        'auth/operation-not-allowed': 'Operación no permitida',
        'auth/weak-password': 'Contraseña débil',
        'auth/internal-error': 'Error interno',
        'auth/invalid-phone-number': 'Número de teléfono inválido',
        'auth/invalid-verification-code': 'Código de verificación inválido',
        'auth/missing-phone-number': 'Falta número de teléfono',
        'auth/missing-verification-code': 'Falta código de verificación',
        'auth/credential-already-in-use': 'Credencial ya en uso',
        'auth/invalid-credential': 'Credencial inválida',
        'auth/operation-not-supported-in-this-environment': 'Operación no soportada en este entorno',
        'auth/invalid-api-key': 'Clave API inválida',
        'auth/invalid-user-token': 'Token de usuario inválido',
        'auth/app-deleted': 'Aplicación eliminada',
    }
}


export const windowLang = (window.navigator.language.split('-')[0] === 'es' || window.navigator.language.split('-')[0] === 'en') ? window.navigator.language.split('-')[0] : 'en';